version: '3'

services:
  db:
    image: postgres

    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - .postgres:/var/lib/postgresql

  db_pgadmin:
    image: dpage/pgadmin4

    env_file:
      - docker.env
    ports:
      - '15432:80'
    depends_on:
      - db

  redis:
    image: redis:alpine
    command: redis-server --requirepass admin
    ports:
      - '6379:6379'
    volumes:
      - .redis:/data
